# Generated by Django 5.0.6 on 2024-07-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_alter_usersettings_preferred_time_ranges_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='preferred_time_ranges',
            field=models.ManyToManyField(related_name='user_settings_set', through='members.UserTimeRange', to='members.timerange'),
        ),
        migrations.AlterUniqueTogether(
            name='timerange',
            unique_together={('day', 'start_time', 'end_time')},
        ),
    ]
