# Generated by Django 5.0.6 on 2024-07-03 17:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_alter_contact_birthday_alter_usersettings_frequency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersettings',
            unique_together={('user', 'group')},
        ),
    ]
