# Generated by Django 5.0.6 on 2024-07-06 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_alter_usersettings_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.contact'),
        ),
        migrations.AddField(
            model_name='notification',
            name='scheduled_meeting_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
