# Generated by Django 5.0.6 on 2024-07-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_recommendation'),
    ]

    operations = [
    ]
