# Generated by Django 5.0.6 on 2024-07-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_alter_usersettings_preferred_end_time_and_more'),
    ]

    operations = [
    ]
