# Generated by Django 5.0.6 on 2024-07-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_alter_usersettings_preferred_days'),
    ]

    operations = [
    ]
