# Generated by Django 5.0.6 on 2024-07-15 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_alter_timerange_unique_together_usertimerange_and_more'),
        ('members', '0022_auto_20240715_0907'),
    ]

    operations = [
    ]
