# Generated by Django 5.0.6 on 2024-07-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0023_merge_20240715_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='new_field',
            field=models.CharField(max_length=100, blank=True),
        ),
    ]
