# Generated by Django 5.0.6 on 2024-07-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0024_alter_usersettings_preferred_time_ranges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='new_field',
        ),
    ]
