# Generated by Django 5.0.6 on 2024-07-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0025_remove_usersettings_new_field_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usertimerange',
            unique_together={('usersettings', 'timerange')},
        ),
    ]
