# Generated by Django 5.0.6 on 2024-07-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0028_meeting_scheduled_time_and_more'),
    ]

    operations = [

    ]
