# Generated by Django 5.0.6 on 2024-07-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0030_alter_usersettings_preferred_time_ranges'),
    ]

    operations = [

    ]
