# Generated by Django 5.0.6 on 2024-07-22 19:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0031_alter_usersettings_preferred_time_ranges'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meeting',
            unique_together={('user', 'group', 'person_met', 'scheduled_time')},
        ),
    ]
