# Generated by Django 5.0.6 on 2024-07-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0034_contact_picture_and_more'),
    ]

    operations = [
    ]
