# Generated by Django 5.0.6 on 2024-07-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0035_alter_usersettings_preferred_time_ranges'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='event',
            field=models.CharField(choices=[('Birthday', 'Birthday'), ('Meeting', 'Meeting')], default='Meeting', max_length=100),
        ),
    ]
