# Generated by Django 5.0.6 on 2024-08-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0037_notification_last_seen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='last_seen',
            field=models.DateTimeField(blank=True, default='Not seen yet', null=True),
        ),
    ]
