# Generated by Django 5.0.6 on 2024-08-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0038_alter_notification_last_seen_and_more'),
    ]

    operations = [
    ]
