# Generated by Django 5.0.6 on 2024-08-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0039_alter_usersettings_preferred_time_ranges'),
    ]

    operations = [
    ]
