# Generated by Django 5.0.6 on 2024-08-12 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0044_usersettings_preferred_time_ranges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='preferred_time_ranges',
        ),
    ]
