# Generated by Django 5.0.6 on 2024-08-12 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0045_remove_usersettings_preferred_time_ranges'),
    ]

    operations = [
    ]
